parameters:
    database_host: localhost
    database_port: null
    database_name: colloque
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 95ea6c490d67e9e5efd90833b499f52404fb600d
