<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwnwuf7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwnwuf7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFwnwuf7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFwnwuf7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFwnwuf7\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fwnwuf7',
    'container.build_id' => '3279de78',
    'container.build_time' => 1530128351,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwnwuf7');
