<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLuln7rn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLuln7rn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLuln7rn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLuln7rn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLuln7rn\appProdProjectContainer(array(
    'container.build_hash' => 'Luln7rn',
    'container.build_id' => 'cdb8df63',
    'container.build_time' => 1530538223,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLuln7rn');
