<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTls82un\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTls82un/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTls82un.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTls82un\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTls82un\appProdProjectContainer(array(
    'container.build_hash' => 'Tls82un',
    'container.build_id' => '91f5d2e1',
    'container.build_time' => 1530695865,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTls82un');
