<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container49sb9yn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container49sb9yn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container49sb9yn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container49sb9yn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container49sb9yn\appDevDebugProjectContainer(array(
    'container.build_hash' => '49sb9yn',
    'container.build_id' => 'afafb6e0',
    'container.build_time' => 1529650617,
), __DIR__.\DIRECTORY_SEPARATOR.'Container49sb9yn');
